// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/_supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.106.1";
function supabaseForUser(ctx) {
  const url = process.env.SUPABASE_URL;
  const anon = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
  return createClient(url, anon, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function requireAuth(ctx) {
  if (!ctx.isAuthenticated()) {
    return {
      ok: false,
      response: {
        content: [{ type: "text", text: "N\xE3o autenticado." }],
        isError: true
      }
    };
  }
  return { ok: true };
}

// src/lib/mcp/tools/whoami.ts
var whoami_default = defineTool({
  name: "whoami",
  title: "Quem sou eu",
  description: "Retorna o usu\xE1rio autenticado (id, e-mail), pap\xE9is (superadmin/admin/equipe) e a institui\xE7\xE3o associada. \xDAtil para conferir o contexto antes de chamar ferramentas que dependem de institui\xE7\xE3o.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    const guard = requireAuth(ctx);
    if (!guard.ok) return guard.response;
    const client = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const [{ data: profile }, { data: roles }] = await Promise.all([
      client.from("profiles").select("id, full_name, role_label, institution").eq("id", userId).maybeSingle(),
      client.from("user_roles").select("role").eq("user_id", userId)
    ]);
    const payload = {
      user_id: userId,
      email: ctx.getUserEmail(),
      profile: profile ?? null,
      roles: (roles ?? []).map((r) => r.role)
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-patients.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^3.25.76";
var list_patients_default = defineTool2({
  name: "list_patients",
  title: "Listar pessoas sob cuidado",
  description: "Lista pacientes vis\xEDveis para o usu\xE1rio autenticado (respeitando RLS por institui\xE7\xE3o). Aceita busca por nome/telefone e filtro por est\xE1gio.",
  inputSchema: {
    search: z.string().trim().min(1).max(120).optional().describe("Trecho do nome ou telefone."),
    stage: z.string().trim().min(1).max(60).optional().describe("Filtro exato de est\xE1gio."),
    limit: z.number().int().min(1).max(100).default(25)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, stage, limit }, ctx) => {
    const guard = requireAuth(ctx);
    if (!guard.ok) return guard.response;
    const client = supabaseForUser(ctx);
    let q = client.from("patients").select("id, full_name, phone, stage, channel_pref, institution, owner_id, created_at").order("created_at", { ascending: false }).limit(limit);
    if (stage) q = q.eq("stage", stage);
    if (search) q = q.or(`full_name.ilike.%${search}%,phone.ilike.%${search}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { patients: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-patient.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z2 } from "npm:zod@^3.25.76";
var get_patient_default = defineTool3({
  name: "get_patient",
  title: "Detalhar paciente",
  description: "Retorna dados do paciente, rede de cuidado e \xFAltimas mensagens. Respeita RLS.",
  inputSchema: {
    patient_id: z2.string().uuid().describe("UUID do paciente."),
    messages_limit: z2.number().int().min(0).max(50).default(10)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ patient_id, messages_limit }, ctx) => {
    const guard = requireAuth(ctx);
    if (!guard.ok) return guard.response;
    const client = supabaseForUser(ctx);
    const [{ data: patient, error }, { data: network }, { data: messages }] = await Promise.all([
      client.from("patients").select("*").eq("id", patient_id).maybeSingle(),
      client.from("care_network_contacts").select("id, relation, full_name, phone, receives_reminders, authorization_status").eq("patient_id", patient_id),
      messages_limit > 0 ? client.from("messages").select("id, direction, channel, status, body, created_at").eq("patient_id", patient_id).order("created_at", { ascending: false }).limit(messages_limit) : Promise.resolve({ data: [] })
    ]);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!patient)
      return {
        content: [{ type: "text", text: "Paciente n\xE3o encontrado ou fora do seu escopo." }],
        isError: true
      };
    const payload = { patient, care_network: network ?? [], recent_messages: messages ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-journeys.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z3 } from "npm:zod@^3.25.76";
var list_journeys_default = defineTool4({
  name: "list_journeys",
  title: "Listar jornadas",
  description: "Lista jornadas vis\xEDveis para o usu\xE1rio (respeita RLS por institui\xE7\xE3o). Aceita filtro por status.",
  inputSchema: {
    status: z3.enum(["draft", "active", "paused", "archived"]).optional(),
    limit: z3.number().int().min(1).max(100).default(25)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    const guard = requireAuth(ctx);
    if (!guard.ok) return guard.response;
    const client = supabaseForUser(ctx);
    let q = client.from("journeys").select("id, name, description, status, institution, created_at, updated_at").order("updated_at", { ascending: false }).limit(limit);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { journeys: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-conversations.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z4 } from "npm:zod@^3.25.76";
var list_conversations_default = defineTool5({
  name: "list_conversations",
  title: "Listar mensagens recentes",
  description: "Retorna as mensagens mais recentes vis\xEDveis para o usu\xE1rio (respeita RLS). Aceita filtro por dire\xE7\xE3o (inbound/outbound).",
  inputSchema: {
    limit: z4.number().int().min(1).max(100).default(25),
    direction: z4.enum(["inbound", "outbound"]).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, direction }, ctx) => {
    const guard = requireAuth(ctx);
    if (!guard.ok) return guard.response;
    const client = supabaseForUser(ctx);
    let q = client.from("messages").select("id, patient_id, direction, channel, status, body, created_at").order("created_at", { ascending: false }).limit(limit);
    if (direction) q = q.eq("direction", direction);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { messages: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "czrstjmhgfewlsetsrvl";
var mcp_default = defineMcp({
  name: "chagas-digital-care-mcp",
  title: "Chagas Digital Care",
  version: "0.1.0",
  instructions: "Ferramentas do Chagas Digital Care. O chamador atua como o pr\xF3prio usu\xE1rio autenticado \u2014 todas as pol\xEDticas de RLS (papel, institui\xE7\xE3o, propriedade) s\xE3o aplicadas. Use `whoami` para inspecionar o contexto do usu\xE1rio conectado, `list_patients`/`get_patient` para consultar pessoas sob cuidado, `list_journeys` para jornadas ativas e `list_conversations` para a caixa de conversas de WhatsApp.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    whoami_default,
    list_patients_default,
    get_patient_default,
    list_journeys_default,
    list_conversations_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
